- Basic Programs/Base Convertor Number System.py
- CONTRIBUTORS.md
Hi, added one basic base convertor system python program which helps to convert the base of number. Please merge and help me contribute open source.
> added base convertor program

- AppendLastNToFirst.cpp
- Bubble Sort (Iterative) LinkedList.cpp
- Code  Merge Sort.cpp
- Code  Reverse LL (Recursive).cpp
- Code Merge Two Sorted LL.cpp
- Code Midpoint of LL.cpp
- Code Reverse LL (Iterative).cpp
- Delete every N nodes.cpp
- Delete(Recursive).cpp
- DeleteNode.cpp
- DeleteNskipM.cpp
- DivideLLInto2.cpp
- Eliminate duplicates from LL.cpp
- Even after Odd LinkedList.cpp
- EvenAfterOddLL.cpp
- Find a Node in Linked List.cpp
- Find a node in LL (recursive).cpp
- Insert(recursive).cpp
- KReverse.cpp
- LenghtofLL(recursive).cpp
- Length of LL.cpp
- LetFirstBeLast.cpp
- PallindromList.cpp
- Print Reverse LinkedList.cpp
- Print ith node.cpp
- Swap two Nodes of LL.cpp
- Swap2nodes.cpp
- UnionLL.cpp
- kReverse.cpp
All basic to advance program for beginners of LinkedList topic
> LINKEDKIST

- Algorithms/C++/Searching/binary_search.cpp
- Algorithms/C++/Searching/fibonacci_search.cpp
- Algorithms/C++/Searching/linear_search.cpp
- Algorithms/C++/Searching/ternary_search.cpp
- Algorithms/C++/Sorting/bubble_sort.cpp
- Algorithms/C++/Sorting/insertion_sort.cpp
- Algorithms/C++/Sorting/merge_sort.cpp
- Algorithms/C++/Sorting/quick_sort.cpp
> Searching & Sorting Algorithms in C++

- rock paper scissors/README.md
- rock paper scissors/rating.txt
- rock paper scissors/rock-paper-scissors.py
Script to Play Rock-Paper-Scissors against computer with more options like  
``` rock, gun, lightning, devil, dragon, water, air, paper, sponge, wolf, tree, human, snake, scissors, fire ```
> Added Rock Paper Scissors

- speech to text/Speech-to-text.py
@all-contributors please add @shaonidutta for code
> added speech to text recognition

- Basic Programs/circularLL.c
circular linked list c file
Co-Authored-By: soham117 <54547662+soham117@users.noreply.github.com>
> circular linked list

- Basic Programs/heap.py
I added a python file for Heap Sort and Priority Queues. I hope this pull request would be merged. Thank you.
> adding heap in python

- Basic Programs/generate_number.cpp
- Basic Programs/generate_string.cpp
- Basic Programs/primechecker.cpp
The 3 programs are :
1. Program to generate a random string of given length.
2. Program to generate a random number of given number of digits
3. Program to chech whether given number is prime or not.
> Added 3 programs in BasicPrograms directory

- Basic Programs/bubbleSort.py
Added a file for bubble sort using python in the Basic programs directory
> :sparkles: Implemented bubblesort in python

- Python A.I/.vscode/settings.json
- Python A.I/jarvis.py
Contribution for Hacktober Fest-2020 pls review and if any issue pls notify me it will be an learning experience for me.Thank You!!
> A.I(Voice Assistant) Using Python

- Basic Programs/digitPrimeChecker.java
This program takes input of a number and checks if the number of digits in it is prime or not and gives output.
> added new digit Prime Checker program

- C/SumOfPolynomials.c
Contributing for Hacktober fest 2020. Do review my work and feel free to point out my mistakes Thank you
> C program for calculating sum of polynomials using singly linked lists

- Basic Programs/ip_checker.py
> Created IP Address Checker

- Notebook/Tree_Traversal.ipynb
Tree traversal like Inorder, Preorder and Postorder.
> Tree traversal python notebook

- Basic Programs/CPP/Code Shell Sort.cpp
Added Shell Sort.cpp in [CPP](https://github.com/aniketsingh98571/HacktoberFest2020-1/tree/aniket/Basic%20Programs/CPP)
@Rishikesh-12 Please review my PR and do let me know if any changes required.
> Added Shell Sort.cpp

- .all-contributorsrc
- Face Detection/Needed Packages.txt
- Face Detection/face_detection.py
- Face Detection/haarcascade_frontalface_default.xml
I add the **Face Detection** Folder which consists of a python file to detect faces live from webcam. It also consists of **haarcascade_frontolface_default** module
> rudrabarad | Face Detection

- .all-contributorsrc
- Bootstrap/forms.html
Reverts Rishikesh-12/HacktoberFest2020#349
> Revert "Revert "Added Bootstrap Project""

- LeetCode_Problem/SameTree.cpp
I created a folder called LeetCode_Problem and add a file with leetCode famous tree problem SameTree.
> added leetCode Problem Folder with SameTree problem

- Algorithms/Java/Binary tree Java/ArbolB.java
- Algorithms/Java/Binary tree Java/Nodo.java
A Java implementation of Binary tree search.
> Java Binary tree search methods

- password generator using python.py
This file consists of a password generator made using python
> Password Generator using python

- JavaScript Mini Projects/Color Flipper Js/README.md
- JavaScript Mini Projects/Color Flipper Js/index.html
- JavaScript Mini Projects/Color Flipper Js/script.js
- JavaScript Mini Projects/Color Flipper Js/styles.css
In this file, I'have added a color flipper.
> Added JavaScript mini projects

- Basic Programs/Selection sort
Hacktoberfest2020
program to implement selection Sort over an array.
> Selection Sort

- Basic Programs/Depth_First_Search.cpp
Added the code with necessary comments for the Depth First Search algorithm
> Added Depth First Search algorithm in C++

- conn.php
- delete.php
- display.php
- insert.php
- update.php
Upload an eCommerce project using CRUD operation using PHP
> Added my php project

- arduino-door_opener/README.md
- arduino-door_opener/door.ino
simple door opener with arduino
> Add Arduino Program

- Basic Programs/CPP/CountAndSay.cpp
> Created CountandSay

- Maze Game/maze.html
Maze Game Web created by JS (JavaScript)
> add maze game web by js

- Python Gst Calculator/GUI_GST.py
Very Basic GST Calculator (GUI) Version using Tkinter
> GST Calculator GUI Version

- Basic Programs/pythagorean_triplet.py
Added a pythagorean triplet written in python as a part of basic program.
> add a basic program

- Invisible cloak/inv_cloak.py
Adding a new project file : The invisible cloak. Its exactly same as the Harry Potters cloak, using open CV it detects a particular color threshold and then using the masking technique makes the effect of green screen
> adding the invisible cloak project file

- Basic Programs/CPP/ImplementStrStr.cpp
Implement strStr().
strstr - locate a substring ( needle ) in a string ( haystack ).
Try not to use standard library string functions for this question.
Returns the index of the first occurrence of needle in haystack, or -1 if needle is not part of haystack.
> Implement strStr()

- Machine_Learning/DecisionTree.py
- Machine_Learning/KNN.py
- Machine_Learning/NaiveBayes.py
- Machine_Learning/README.md
@all-contributors please add @<hvijaycse> for <code>
> Ml algorithms

- Perfect Number Logic in C++
When the sum of the factors of a number, excluding itself is same as the number, the number is called a PERFECT number. This piece of code contains a function that tests whether the giver number is a perfect number or not and the main() function to drive the program.
> Perfect Number Logic in C++

- Algorithms/C++/Dijkstra Algorithm.cpp
Dijkstra's algorithm is an algorithm for finding the shortest paths between nodes in a graph, which may represent, for example, road networks.
> Added Dijkstra Algorithm

- Basic Programs/UpdatingArrayMultiplications
Given a array update every element with multiplication of previous and next element  with a exception  that
1)First element  is replaced by multiplication of first and second
2)Last element  is replaced by multiplication of last and second last
> Create Updating Elements of Array by Multiplication

- number predict game
predict a number between 1-20. than if the number is correct than you win or the number is incorrect than guess another number untill the right number .
> python number game

- Basic Programs/swapping two numbers without a third variable.cpp
A cpp code to implement swapping of two numbers without using a third variable.
@all-contributors please add @khushimishra26  for💻 code
> swapping two numbers without using a third variable.

- Basic Programs/Palindrome.java
- Basic Programs/anagram.java
- Basic Programs/characterOccurrence.java
- Basic Programs/reverseEachWord.java
- Basic Programs/stringReverse.java
Java Programs on important string problems
> Program on Anagram, Character Occurrence, Reverse each string word, Palindrome, Reversal of string 

- Counting CL Nodes.c
Counting Nodes of Circular Linked Lists using CPP
> Counting Nodes

- Color Game/colorGame.css
- Color Game/colorGame.html
- Color Game/colorGame.js
A Color Game to enhance your knowledge over colors
> Added a Color Game written in HTML, CSS and JS

- Basic Programs/CPP/TransposeOfMatrix.cpp
@all-contributors please add @akshaykrad for TransposeOfMatrix code
> This program can give the transpose of a matrix

- Basic Programs/string_reversal.py
- Basic Programs/swapping two numbers without a third variable.cpp
a simple python program for reversing any inputted string.
@all-contributors please add @khushimishra26  for 💻 code
> Some basic cpp and python programs

- mergeSort_OOP.cpp
- quickSort_OOP.cpp
Making this pull request with reference to issue #54 
Requesting to review and merge!
> Adding sorting algorithms using OOP in C++

- C/C program for Time Complexity plot of Bubble, Insertion and Selection Sort
its a c program for Time Complexity plot of Bubble, Insertion and Selection sort
> C program for Time Complexity plot of Bubble, Insertion and Selection sort

- To-do/README.md
- To-do/app.js
- To-do/index.html
- To-do/style.css
This is a "To Do" list which can store all entries until you delete them.
It has separate columns for "complete" and "incomplete" tasks.
> To Do Application using HTML, CSS and JS

- Basic Programs/binary search.cpp
- Basic Programs/even odd elements sum .cpp
- Basic Programs/one dimensional array reversal.cpp
- Basic Programs/string_reversal.py
- Basic Programs/swapping two numbers without a third variable.cpp
Some basic cpp programs related to arrays (one-dimensional)
> Basic c cpp programs

- N- Queens-Problem.java
> Create N- Queens-Problem.java

- Basic Programs/reverseArray.cpp
I added a cpp file , accept this pull Request and merge it
> Add reverseArray.cpp file

- Algorithms/C++/Dynamic Programming/knapsack_problem.cpp
- Algorithms/C++/Dynamic Programming/longest_increasing_subsequence.cpp
Added a sub section for DP problems in the Algorithms/C++ folder
> added dynamic programming problem section

- text to Speech/textSpeak.py
Text-to-Speech Python Program. Create a new folder for text-to-speech
> Text_to_Speech Python Program

- Basic Programs/Kth row of pascal's triangle.java
- Basic Programs/Trailing Zeros in Factorial.java
Added some basic java programs.
> Added Java codes

- python_port_scanner.py
> port scanner

- Basic Programs/CPP/sum_very_large_numbers.cpp
Hi, I am Mukund Agarwal. I have added a new program and made the commits and also raised the PR. Thanks.
> added by mk15012

- Basic Programs/ReverseDigits.java
A simple Java program to reverse the digits of a given number.
> Added ReverseDigits.java

- Basic Programs/hi.js
Reverts Rishikesh-12/HacktoberFest2020#222
> Revert "created a hello world in javascript"

- Basic Programs/Hello.py
Reverts Rishikesh-12/HacktoberFest2020#30
> Revert "created hello world in python"

- python/hello_world.py
Reverts Rishikesh-12/HacktoberFest2020#205
> Revert "hello world program in python"

- Algorithms/C++/Sorting/Selection sort.cpp
Sorting Algorithm - Selection Sort
> Selection Sort.cpp

- facebook-login-page/package.json
- facebook-login-page/public/index.html
- facebook-login-page/src/App.js
- facebook-login-page/src/Facebook.js
- facebook-login-page/src/Facebook.module.css
- facebook-login-page/src/index.js
Hi,
I have added the Facebook login page built using React and CSS Modules with full functionality and ready to be used in any project. Please review and merge this pr.
Thanks!
> FacebookLoginPage by Rishav

- Basic Programs/pattern_pyramid.py
Input taken and function called
> Updated pattern_pyramid.py

- python_pathvisualizer/Spots.py
- python_pathvisualizer/bfs_visualizer.py
- python_pathvisualizer/dfs_visualization.py
Python path visualizer using pygame
> python path visaulizer

- Algorithms/Python/radixSort.py
Hi maintainer,
Thank you for giving this opportunity. 
I added a folder named Python with logic of Radix sort in an existing folder named Algorithms.
If you find my Pull request to be valid, kindly merge it. 
Thanking you. 
Simran Anand.
> Added a folder named Python with logic of Radix sort using Python lang

- Python Turtle/Spiralling Square.py
Hey, I created a hypnotic/spiralling square using Python Turtle using commands like pencolor(), fd(), lt() etc.
> Create Spiralling Square.py

- Basic Programs/GCD using python.py
- Basic Programs/Number reversal.py
- Basic Programs/Reversing string.py
- Basic Programs/Temperature conversion (Celsius to fahrenheit).py
- Basic Programs/binary search.cpp
- Basic Programs/even odd elements sum .cpp
- Basic Programs/one dimensional array reversal.cpp
- Basic Programs/string_reversal.py
- Basic Programs/swapping two numbers without a third variable.cpp
Added some basic python codes as well.
> Some basic python programs

- Permutation of A String
Permutation of A  given String
> Permutation of A String

- Algorithms/C++/Greedy Algorithm/CoveringSegments.cpp
I have added one greedy Algorithm based on C++
Question Description is mention in the file
Please @Rishikesh-12 accept it
> Added One Greedy Algorithm

- Basic Programs/CPP/Permutations.cpp
This algorithm displays al the possible permutations of a string using recursion.
> Code to find Permutations of a string using recursion

- Basic Programs/binaryAddition.java
java code to add two binary strings without using inbuilt functions
> binary addition

- Basic Programs/JustABox.py
- C/Pyramid.cpp
> happy hacktoberfest2020
